artikel/urls.py
from django.urls import path
from .views import ArtikelListView, ArtikelDetailView, ArtikelKategoriListView

urlpatterns = [
	path('kategori/<str:kategori>/', ArtikelKategoriListView.as_view(), name='category'),
	path('kategori/<str:kategori>/<int:page>', ArtikelKategoriListView.as_view(), name='category'),
	path('<slug:slug>/', ArtikelDetailView.as_view(), name='detail'),
	path('page/<int:page>', ArtikelListView.as_view(), name='list'),
	path('', ArtikelListView.as_view(), name='list'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.views.generic import TemplateView

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include(('artikel.urls', 'artikel'), namespace='artikel')),
	# path('', TemplateView.as_view(template_name = 'index.html'), name='home'),
]

artikel/models.py
from django.db import models
from django.utils.text import slugify

class Artikel(models.Model):
	judul		= models.CharField(max_length=255)
	isi			= models.TextField()
	gambar		= models.CharField(max_length=255)
	kategori	= models.CharField(max_length=255, blank=True)
	published	= models.DateTimeField(auto_now_add=True)
	updated		= models.DateTimeField(auto_now=True)
	slug		= models.SlugField(blank=True, editable=False)
	
	def save(self):
		self.slug = slugify(self.judul)
		super().save()
	def __str__(self):
		return "{}. {}".format(self.id, self.judul)

artikel/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import	Artikel

class ArtikelKategoriListView(ListView):
    model = Artikel
    template_name = "artikel/artikel_kategori_list.html"
    context_object_name = 'artikel_list'
    ordering = ['-published']
    paginate_by = 3
 
    def get_queryset(self):
        self.queryset = self.model.objects.filter(kategori=self.kwargs['kategori'])
        return super().get_queryset()

    def get_context_data(self, *args, **kwargs):
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct().exclude(kategori = self.kwargs['kategori'])
        self.kwargs.update({'kategori_list' : kategori_list})
        kwargs = self.kwargs
        return super().get_context_data(*args,**kwargs)

class ArtikelListView(ListView):
    model = Artikel
    template_name = "artikel/artikel_list.html"
    context_object_name = 'artikel_list'
    ordering = ['-published']
    paginate_by = 3

    def get_context_data(self, *args, **kwargs):
    	kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
    	self.kwargs.update({'kategori_list' : kategori_list})
    	kwargs = self.kwargs
    	return super().get_context_data(*args,**kwargs)

class ArtikelDetailView(DetailView):
    model = Artikel
    template_name = "artikel/artikel_detail.html"
    context_object_name = 'artikel'

    def get_context_data(self, *args, **kwargs):
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
        self.kwargs.update({'kategori_list' : kategori_list})
        artikel_serupa = self.model.objects.filter(kategori=self.object.kategori).exclude(id=self.object.id)
        self.kwargs.update({'artikel_serupa' : artikel_serupa})
        kwargs = self.kwargs
        return super().get_context_data(*args,**kwargs)

artikel/templates/artikel/artikel_detail.html
{% extends "base.html" %}

{% block page_title %}
	{{artikel.judul}}
{% endblock page_title %}

{% block contents %}
	<div class="row">
		<div class="col-sm-8">
			<h2>{{artikel.judul}}</h2>
			<h6>Kategori: {{artikel.kategori}} | {{artikel.published|date}}</h6>
			<p>{{artikel.isi}}</p>	
		</div>
		<div class="col-sm-4">
			<h3>Kategori</h3>
			<ul class="list-group list-group-flush">
				{% for kategori in kategori_list %}
				<li class="list-group-item"><a href="{% url 'artikel:category' kategori %}">{{kategori}}</a></li>
				{% endfor %}  
			</ul>
			<h3>Artikel Serupa</h3>
			<ul class="list-group list-group-flush">
				{% for artikel in artikel_serupa %}
					{% if forloop.counter is not 4 %}
					<li class="list-group-item">
						<h6><a href="{% url 'artikel:detail' artikel.slug %}">{{artikel.judul}}</a></h6>
						<small>{{artikel.published|date}}</small>
					</li>
					{% endif %}
				{% endfor %}  
				<li class="list-group-item"><a href="{% url 'artikel:category' artikel.kategori %}">Selengkapnya</a></li>
			</ul>
		</div>
	</div>
{% endblock contents %}

artikel/templates/artikel/artikel_kategori_list.html
{% extends "base.html" %}

{% block page_title %}
	Artikel
{% endblock page_title %}

{% block contents %}
<div class="row">
	<div class="col-8">
		{% for artikel in artikel_list %}
		<h3><a class="text-dark" href="{% url 'artikel:detail' artikel.slug %}">{{artikel.judul}}</a></h3>
		<p>Kategori: {{artikel.kategori}} | {{artikel.published|date}}</p>
		<p>{{artikel.isi|truncatewords:50}} <a href="{% url 'artikel:detail' artikel.slug %}">Selengkapnya</a></p>
		{% endfor %}
		{% if is_paginated %}
		<nav aria-label="artikelPage">
		  <ul class="pagination">
		    {% if page_obj.has_previous %}
		     	<li class="page-item">
		     		<a class="page-link" href="{% url 'artikel:category' kategori page_obj.previous_page_number %}">Previous</a>
		     	</li>
		     {% else %}
			     <li class="page-item disabled">
			     	<span class="page-link">Previous</span>
			    </li>
		     {% endif %}     
			{% for page in paginator.page_range %}
			{% if page is page_obj.number %}
				<li class="page-item active">
			      <span class="page-link">
			        {{page}}
			        <span class="sr-only">(current)</span>
			      </span>
		    	</li>
		    {% else %}
		    	<li class="page-item"><a class="page-link" href="{% url 'artikel:category' kategori page %}">{{page}}</a></li>
			{% endif %}
			{% endfor %}
		    	{% if page_obj.has_next %}
		     	<li class="page-item">
		     		<a class="page-link" href="{% url 'artikel:category' kategori page_obj.next_page_number %}">Next</a>
		     	</li>
		    	{% else %}
			    <li class="page-item disabled">
			     	<span class="page-link">Next</span>
			    </li>
		     {% endif %}     
		  </ul>
		</nav>
	{% endif %}
	</div>
	<div class="col-4">
		<h3>Kategori</h3>
		<ul class="list-group list-group-flush">
			{% for kategori in kategori_list %}
			<li class="list-group-item"><a href="{% url 'artikel:category' kategori %}">{{kategori}}</a></li>
			{% endfor %}  
		</ul>
	</div>
</div>
{% endblock contents %}

artikel/templates/artikel/artikel_list.html
{% extends "base.html" %}

{% block page_title %}
	Artikel
{% endblock page_title %}

{% block contents %}
<div class="row">
	<div class="col-8">
		{% for artikel in artikel_list %}
		<h3><a class="text-dark" href="{% url 'artikel:detail' artikel.slug %}">{{artikel.judul}}</a></h3>
		<p>Kategori: {{artikel.kategori}} | {{artikel.published|date}}</p>
		<p>{{artikel.isi|truncatewords:50}} <a href="{% url 'artikel:detail' artikel.slug %}">Selengkapnya</a></p>
		{% endfor %}
		{% if is_paginated %}
		<nav aria-label="artikelPage">
		  <ul class="pagination">
		    {% if page_obj.has_previous %}
		     	<li class="page-item">
		     		<a class="page-link" href="{% url 'artikel:list' page_obj.previous_page_number %}">Previous</a>
		     	</li>
		     {% else %}
			     <li class="page-item disabled">
			     	<span class="page-link">Previous</span>
			    </li>
		     {% endif %}     
			{% for page in paginator.page_range %}
			{% if page is page_obj.number %}
				<li class="page-item active">
			      <span class="page-link">
			        {{page}}
			        <span class="sr-only">(current)</span>
			      </span>
		    	</li>
		    {% else %}
		    	<li class="page-item"><a class="page-link" href="{% url 'artikel:list' page %}">{{page}}</a></li>
			{% endif %}
			{% endfor %}
		    	{% if page_obj.has_next %}
		     	<li class="page-item">
		     		<a class="page-link" href="{% url 'artikel:list' page_obj.next_page_number %}">Next</a>
		     	</li>
		    	{% else %}
			    <li class="page-item disabled">
			     	<span class="page-link">Next</span>
			    </li>
		     {% endif %}     
		  </ul>
		</nav>
	{% endif %}
	</div>
	<div class="col-4">
		<h3>Kategori</h3>
		<ul class="list-group list-group-flush">
			{% for kategori in kategori_list %}
			<li class="list-group-item"><a href="{% url 'artikel:category' kategori %}">{{kategori}}</a></li>
			{% endfor %}  
		</ul>
	</div>
</div>
{% endblock contents %}

templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">	
	<title>{% block page_title %}{% endblock page_title %}</title>
	{% include "snippets/styles.html" %}
</head>
<body>
	{% include "snippets/navbar.html" %}

	<div class="container mtop">	
		{% block contents %}
			
		{% endblock contents %}
	</div>

	{% include "snippets/scripts.html" %}
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block page_title %}
	Home
{% endblock page_title %}

{% block contents %}
	Content
{% endblock contents %}

templates/snippets/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
	<div class="container">
		<a class="navbar-brand" href="#">Blog</a>
	  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
	<div class="collapse navbar-collapse" id="navbarNavDropdown">
	    <ul class="navbar-nav">
	      <li class="nav-item active">
	        <a class="nav-link" href="{% url 'artikel:list' %}">Home</a>
	      </li>
	    </ul>
	  </div>
	  <div class="nav-item dropdown ml-auto">
	        <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          User
	        </a>
	        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
	          <a class="dropdown-item" href="#">Tambah artikel</a>
	          <a class="dropdown-item" href="#">Manage artikel</a>
	        </div>
	    </div>
	</div>
</nav>

templates/snippets/scripts.html
{% load static %}<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
	<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

templates/snippets/styles.html
{% load static %}<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'vendor/css/style.css' %}">